### ISSUE TITLE
Hudbars support

### ISSUE THREAD

**Issue by tacotexmex** [4w/hunger_ng#2]
How about supporting Wuzzy's hudbars? It's stable and widely used.

**Comment by 4w** [comment]
This won’t happen if the mod needs to depend on it. While hudbars actually IS widely used I want the mod to be completely self-contained.

I could add a setting for not hiding the hunger bar when the breath bar is shown so it won’t disappear when other mods move it around if that helps.

**Comment by tacotexmex** [comment]
Thinking it could support it but not depend on it, making it suit non-hudbar and hudbar-games alike. Just like i did in my mod hbSprint.

**Comment by 4w** [comment]
Here you go :smile: 

Do you know how to get the nice frame/background around the bar like the health bar has?

![s](https://user-images.githubusercontent.com/30605057/36266060-e95d1b0e-1270-11e8-8241-c38fbaf5a4ca.png)

**Comment by tacotexmex** [comment]
That'd be the `hudbars_bar_background` image, but I believe it should be applied automatically… 😕 Here's [how I did it](https://github.com/minetest-mods/hbsprint/blob/master/init.lua#L119-L124).

**Comment by 4w** [comment]
Mmhm, I manually added it now in 6386496e63789d1ab592c4e235cf2726e58354a2 but it seems not to do anything. When setting the file name as `bar` then the image gets printed so basically it works to use the default texture from the mod it just seems to ignore the background completely.

**Comment by tacotexmex** [comment]
Only difference I can spot in your hudbar registration code is that you use `'` and not `"`, `'` around `0xFFFFFF` when I don't, and that I have `"%s: %.1f/%.1f"` (can't remember what it does) last in the registration and you don't.

**Comment by 4w** [comment]
LOL, wtf … When using `player:hud_remove()` on an HUD element that is not created by `hudbars` after a HUD bar was initiated it loses it’s background, but only if it was the first created HUD bar.

Well, anyways, it’s fixed. Just get the latest version and try.

**Comment by 4w** [comment]
Implementation done in referenced issues.
