### ISSUE TITLE
Double hunger bars

### ISSUE THREAD

**Issue by tacotexmex** [4w/hunger_ng#5]
![](https://user-images.githubusercontent.com/25328789/36634922-8ff60948-19ac-11e8-9348-dfaf936b29fb.png)
I'm getting dual hunger bars when using the mod with HEAD. (63bcd33 specifically)

**Comment by 4w** [comment]
Related to [this](https://forum.minetest.net/viewtopic.php?p=312300#p312300), right? :smile:  There is nothing I can do about. Wuzzy need’s to check/alter/fix their mod.

Hunger NG is (like all my other mods) tested and compatible with the most recent stable release version of Minetest only.

I tried to reproduce the problem in Minetest 0.4.16 and the latest versions of *HUD Bars* and *Hunger NG* and I was not able to reproduce the issue.

**Comment by tacotexmex** [comment]
Yes of course 😊

**Comment by 4w** [comment]
@tacotexmex See the latest version. It allows to disable the default hunger bar via configuration. It won’t be registered and won’t be shown or altered at all. Hunger itself and all interoperability functionality works like before.

Just set `hunger_ng_use_hunger_bar` to `false` in the advanced configuration or directly in `minetest.conf`.

I hope that helps.

**Comment by tacotexmex** [comment]
That's great, thanks 4w.
