### ISSUE TITLE
Consolidate globalstep registrations

### ISSUE THREAD

**Issue by tacotexmex** [4w/hunger_ng#6]
I count five individual globalstep timers in the mod. In [this discussion](https://github.com/minetest-mods/item_drop/commit/e84433d41ccd4abec1795acbcebe2895bc5be380#commitcomment-24123744) I learned that globalstep means more overhead than `minetest.after` timers.

Would it be beneficial to switch to `after` timers? I'm planning on doing that myself for my mods.

**Comment by 4w** [comment]
`minetest.after` has one big flaw: it needs to recursively call itself over and over again. It  just feels wrong to me that a recurring timed event needs to call itself for the next execution of said event.

Plus: https://github.com/minetest/minetest/issues/5488

Also see this reply: https://forum.minetest.net/viewtopic.php?p=310916#p310916

**Comment by tacotexmex** [comment]
I see, the arguments are quite sound. I keep learning new things about all this engine stuff, it's interesting.

Thinking of the "C++ -> Lua escape" mentioned by sofar and 

> I personally would recommend consolidating all of your tasks into the fewest number of globalstep registrations possible (preferably one or two, if possible)

said by sorcerykid the optimization I then can see to be worth looking into is the consolidation part (five globalstep registrations merged into one)

**Comment by 4w** [comment]
Yes, merging the globalsteps is on my personal roadmap.

**Comment by 4w** [comment]
* [ ] Export workloads of single globalsteps to individual functions but keep timer-handling separate from the functions so the functions are only called when the timers are up.
* [ ] Create timer-less universal globalstep
    * [ ] Implement individual timers and timer handling within this globalstep
    * [ ] Run the functions when the timers are up but keep "show/ hide hunger bar" globalstep independent.
        * [ ] heal
        * [ ] starve
        * [ ] base
        * [ ] movement

**Comment by 4w** [comment]
Implemented as described in referenced commit.
